---
- hosts: localhost
  gather_facts: false
  tasks:
    - add_host:
        name: "{{ host }}"
        group: check

- hosts: check
  gather_facts: false
  tasks:
    - include_role:
        name: check_environment
