---
- name: Create database user with name with privileges
  community.mysql.mysql_user:
    name: "{{user}}"
    password: "{{password}}"
    priv: '*.*:ALL'
    state: present

- name: Create a new database
  community.mysql.mysql_db:
    name: "{{db_name}}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
