---
- name: Create a new database
  community.mysql.mysql_db:
    name: "{{db_name}}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create table to database {{db_name}}
  community.mysql.mysql_query:
    query:
      - USE `"{{db_name}}"`; 
      - CREATE TABLE Persons (PersonID int, LastName varchar(255), FirstName varchar(255), City varchar(255));
    login_unix_socket: /run/mysqld/mysqld.sock
