---
- name: Get version from MySQL
  community.mysql.mysql_info:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    filter:
      - version
  register: ms_version

- debug:
    var: ms_version.version.full

- name: Create a motd file with MySql version
  ansible.builtin.template:
    src: templates/motd
    dest: /etc/motd
