---
- name: Set password for user on mysql
  ansible.builtin.shell: 'mysql -e "{{item}}"'
  with_items:
    - FLUSH PRIVILEGES;
    - ALTER USER "'{{user}}'"@'localhost' IDENTIFIED BY "'{{password}}'";

- name: Remove skip-grant-tables from mysql file sock
  ansible.builtin.lineinfile:
    path: /etc/my.cnf
    state: absent
    regexp: '^%skip-grant-tables'

- name: Restart mysql service
  ansible.builtin.service:
    name: mysqld
    state: restarted

- name: Get version from MySQL
  community.mysql.mysql_info:
    config_file: /root/.my.cnf
    filter:
      - version
  register: ms_version

- debug:
    var: ms_version.version.full

- name: Create a motd file with MySql version
  ansible.builtin.template:
    src: templates/motd
    dest: /etc/motd
