---
- name: Get version from MySQL
  community.mysql.mysql_info:
    config_file: /root/.my.cnf
    filter:
      - version
  register: ms_version

- debug:
    var: ms_version.version.full

- name: Create a motd file with MySql version
  ansible.builtin.template:
    src: templates/motd
    dest: /etc/motd
