---
- name: Create database user to connect in all databases
  community.mysql.mysql_info:
    config_file: /root/.my.cnf
    filter:
      - version
  register: ms_version

- debug:
    var: ms_version.stdout_lines
