---
# tasks file for roles/mysql
- name: Install mysql-server
  yum:
    name: mysql-server
    state: present

- name: Start service mysql
  service:
    name: mysqld
    state: started
    enabled: true
