---
- name: Install mysql-server
  ansible.builtin.yum:
    name: mysql-server
    state: present

- ansible.builtin.wait_for:
    timeout: 30

- name: Start service mysql
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: true
  ignore_errors: yes

- name: Get status service
  ansible.builtin.shell: service mysqld status
  register: service_status

- debug:
    msg: "{{service_status.stdout_lines[2] | replace('     ','')}}"

- name: Configure username to access database
  ansible.builtin.lineinfile:
    path: /root/.my.cnf
    insertafter: "[client]"
    line: "{{item}}"
  with_items:
    - "user={{user}}"
    - "password={{password}}"
  
