---
# tasks file for roles/mysql
- name: Install mysql-server
  yum:
    name: mysql-server
    state: present

- name: Start service mysql
  service:
    name: mysqld
    state: started
    enabled: true

- name: Create user to access database
  community.mysql.mysql_user:
    name: "{{user}}"
    password: "{{password | password_hash('sha512')}}" 
    priv: '*.*:ALL'
